// <auto-generated />
using System;
using BlazorBlog.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorBlog.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221023103004_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11");

            modelBuilder.Entity("BlazorBlog.Shared.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Me",
                            Content = "Lorem Ipsum Dolor sit Atmet",
                            DateCreated = new DateTime(2022, 10, 23, 12, 30, 4, 920, DateTimeKind.Local).AddTicks(9707),
                            Description = "This is a bad blog",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "Lol",
                            Url = "new-blog2"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Me",
                            Content = "Lorem Ipsum Dolor sit Atmet",
                            DateCreated = new DateTime(2022, 10, 23, 12, 30, 4, 920, DateTimeKind.Local).AddTicks(9788),
                            Description = "This is a bad blog",
                            IsDeleted = false,
                            IsPublished = true,
                            Title = "Lol2",
                            Url = "new-blog1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
